### ISSUE TITLE
/tags页面报错；文章页面下没有侧边内容导航widget

### ISSUE THREAD

**Issue by hieverest** [YenYuHsuan/hexo-theme-beantech#4]
您好，很喜欢你的主题。但是在部署到我的博客上后，出现一些问题，我慢慢琢磨出了一些，但是还剩两个问题我苦思不得其解……希望您有空能帮我看下：

1. https://hieverest.github.io/tags/  页面报错，提示: 
```
GET https://hieverest.github.com/js/jquery.tagcloud.js 
async	@	(index):776
(anonymous)	@	(index):803
```
造成tag_cloud呈现出现问题。我查看过你demo页面的代码，我们是一模一样的；

2. 我设置了`side-bar: true`，但是打开文章时侧边栏没有文章内容导航，并且侧面有一个scroll bar，我测试了下去掉article标签可消除掉这个bar，但是文章内容导航还是不知道该如何设置。

具体您可以查看我的博客，谢谢！

**Comment by YenYuHsuan** [comment]
@hieverest Here is the 
1. Hi, i've check your blog, but it seems well to me.
2. the article navigation is called table of content (*toc*) and my variable is using `catalog`
you need to enable it from each of your posts.
see my `hexo-theme-beantech.md` for example:
```yaml
title: "[Hexo] Theme BeanTech"
catalog: true
date: 2017-03-18 10:51:24
subtitle: "This is hexo theme Demo."
header-img: "Demo.png"
tags:
- Hexo
- Blog
catagories:
- Hexo
```
`catalog: true` is to enable the *toc*

Peace!
